repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.5
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.4
  hooks:
    - id: check-github-workflows
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.12.1]
