version: 2
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
      - uv sync --frozen --group docs
