[tox]
requires = tox-uv
envlist =
    lint
    py{310,311,312,313,314}
    py310-lowest

[testenv]
runner = uv-venv-lock-runner
dependency_groups = tests
deps =
    lowest: nltk==3.9
commands = pytest {posargs}


[testenv:lint]
dependency_groups = lint
skip_install = true
commands =
    pre-commit run --all-files

[testenv:docs]
dependency_groups = docs
commands = sphinx-build docs/ docs/_build {posargs}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
runner = uv-venv-runner
deps = sphinx-autobuild
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch CONTRIBUTING.rst --watch README.rst

[testenv:readme-serve]
runner = uv-venv-runner
deps = restview
skip_install = true
commands = restview README.rst
